name: Gradle Build

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # required for creating/uploading to releases

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: burrunan/gradle-cache-action@v3.0.1
        name: Build Terra
        with:
          arguments: build
          gradle-version: wrapper
          properties: |
            kotlin.js.compiler=ir
            kotlin.parallel.tasks.in.project=true

      # Create a draft release
      - name: Create draft release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: draft-${{ github.run_id }}
          name: "Draft build ${{ github.run_id }}"
          draft: true
          generate_release_notes: true

      # Upload built JARs to the draft release
      - name: Upload JARs
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
          tag_name: draft-${{ github.run_id }}